### ISSUE TITLE
Atom - categories parsing approach incorrect?

### ISSUE THREAD

**Issue by cpwood** [arminreiter/FeedReader#38]
The [approach for parsing Atom categories](https://github.com/arminreiter/FeedReader/blob/master/FeedReader/Feeds/Atom/AtomFeedItem.cs#L99) appears to be incorrect. I believe that this:

```csharp
var categories = item.GetElements("category");
this.Categories = categories.Select(x => x.GetValue()).ToList();
```

should in fact be this:

```csharp
var categories = item.GetElements("category");
this.Categories = categories.Select(x => (string)x.Attribute("term")).ToList();
```

* [Supporting documentation](https://validator.w3.org/feed/docs/atom.html#category)
* [Example Feed](https://wiganwarriors.com/blog/feed/atom/)

**Comment by arminreiter** [comment]
thanks for the providing the fix and the links to all documentation. its fixed in last version 1.2.4.
